---
apache_enablerepo: ""

apache_listen_ip: "*"
apache_listen_port: 80
apache_listen_port_ssl: 443

apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"

# On Debian/Ubuntu, a default virtualhost is included in Apache's configuration.
# Set this to `true` to remove that default.
apache_remove_default_vhost: true

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html

apache_vhosts:
  # Additional properties: 'serveradmin, serveralias, extra_parameters'.
  - servername: "{{ server_fqdn }}"
    extra_parameters: redirect permanent / https://{{ server_fqdn }}

apache_vhosts_ssl:
   # Additional properties: 'serveradmin, extra_parameters'.
   - {
     servername: "{{ server_fqdn }}",
     documentroot: "/var/www/html",
     certificate_file: "/etc/ssl/certs/server.crt",
     certificate_key_file: "/etc/ssl/certs/server.key",
    }
  #   # Optional.
  #   certificate_chain_file: "/path/to/certificate_chain.crt"

apache_ignore_missing_ssl_certificate: false
apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

# Only used on Debian/Ubuntu.
apache_mods_enabled:
  - rewrite.load
  - ssl.load
apache_mods_disabled: []

# Set initial apache state. Recommended values: `started` or `stopped`
apache_state: started